# Generated by Django 3.1.7 on 2021-11-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20211129_0228'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportcard',
            table=None,
        ),
    ]
